### PR TITLE
Native version update & major release

### PR DESCRIPTION
**Pull request by rgomezp**
# Description
## One Line Summary
Update native XCFrameworks version range and make major release.

## Details
Makes this plugin compatible with the React Native SDK as they're currently out of sync.

### Motivation
Fixes https://github.com/OneSignal/onesignal-expo-plugin/issues/193
Fixes https://github.com/OneSignal/onesignal-expo-plugin/issues/182

### Scope
- iOS pod version range
- Plugin version number (major release)

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have personally tested this on my device, or explained why that is not possible
   - [x] I have tested this on the latest version of the plugin
   - [x] I have tested this on both Android and iOS, or explained why that is not possible
      - Tested on iOS. No Android related changes.

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

### CODE REVIEW

**Review by aindong — APPROVED** [review]
looking forward to this update, atm while this patch is still not merged, we have to use patch-package

**Review by aindong — CHANGES_REQUESTED** [review]
You might also need to update `/support/serviceExtensionFiles/NotificationService.m` 
from `#import <OneSignal/OneSignal.h>` to `#import <OneSignalFramework/OneSignalFramework.h>`

since the react-native-onesignal 5.x now uses `OneSignalFramework.h` instead of `OneSignal.h` 

to

**Comment by pettomartino** [comment]
I tried to apply this MR as patch and faced the issue @aindong is mentioning. The iOS version doesn't compile.

**Comment by rgomezp** [comment]
I've updated the .m file. Thanks @aindong  for catching that.

@pettomartino can you apply this branch again?

**Comment by lele0108** [comment]
@jkasten2 @jennantilla Possible to prioritize reviewing this small but important change? Blocking use of SDK 5 alongside Expo / EAS.

**Comment by pettomartino** [comment]
@rgomezp tested and worked!

**Review by jkasten2 — APPROVED** [review]

**Pull request merged**
